name: Build C++ EXE

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 配置 MSBuild 环境
      uses: microsoft/setup-msbuild@v1.1

    - name: 编译解决方案
      run: msbuild GDModdingTool.sln /p:Configuration=Release /p:Platform=x64

    - name: 上传打包好的 EXE
      uses: actions/upload-artifact@v3
      with:
        name: GDModdingTool-EXE
        path: x64/Release/GDModdingTool.exe
